name: 10
 Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: linux-runner-01
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello from the self-hosted runner in Azure!!!"

      - name: Show system info
        run: uname -a
