name: 10
 Test Self-Hosted Runner

on:
  workflow_dispatch
  
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello from the self-hosted runner in Azure!!!"

      - name: Show system info
        run: uname -a
